// packages/vue/src/components/Pagination/Pagination.vue
<script setup lang="ts">
import { computed } from "vue";

import Button from "../Button/Button.vue";

import {
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
} from "../../icons";

import { DOTS, getPaginationRange } from "./Pagination.utils";

import type { PaginationProps } from "./Pagination.types";

defineOptions({
  name: "Pagination",
});

const props = withDefaults(defineProps<PaginationProps>(), {
  siblingCount: 1,
  buttonVariant: "primary",
  buttonSize: "md",
  buttonRounded: false,
});

const emit = defineEmits<{
  pageChange: [number];
}>();

const totalPages = computed(() =>
  Math.max(1, Math.ceil(props.total / props.pageSize)),
);

const currentPage = computed(() =>
  Math.min(Math.max(props.page, 1), totalPages.value),
);

const pages = computed(() =>
  getPaginationRange({
    total: props.total,
    page: currentPage.value,
    pageSize: props.pageSize,
    siblingCount: props.siblingCount,
  }),
);

function goToPage(page: number) {
  if (page < 1 || page > totalPages.value || page === currentPage.value) {
    return;
  }

  emit("pageChange", page);
}
</script>

<template>
  <nav class="flex items-center justify-center gap-2" aria-label="Pagination">
    <Button
      :variant="buttonVariant"
      :size="buttonSize"
      :rounded="buttonRounded"
      aria-label="Go to first page"
      :disabled="currentPage === 1"
      @click="goToPage(1)"
    >
      <ChevronsLeftIcon />
    </Button>

    <Button
      :variant="buttonVariant"
      :size="buttonSize"
      :rounded="buttonRounded"
      aria-label="Go to previous page"
      :disabled="currentPage === 1"
      @click="goToPage(currentPage - 1)"
    >
      <ChevronLeftIcon />
    </Button>

    <template v-for="(item, index) in pages" :key="`${item}-${index}`">
      <span v-if="item === DOTS" class="px-2 text-gray-500" aria-hidden="true">
        ...
      </span>

      <Button
        v-else
        :variant="buttonVariant"
        :size="buttonSize"
        :rounded="buttonRounded"
        :appearance="currentPage === item ? 'solid' : 'outline'"
        :aria-label="`Page ${item}`"
        :aria-current="currentPage === item ? 'page' : undefined"
        @click="goToPage(item)"
      >
        {{ item }}
      </Button>
    </template>

    <Button
      :variant="buttonVariant"
      :size="buttonSize"
      :rounded="buttonRounded"
      aria-label="Go to next page"
      :disabled="currentPage === totalPages"
      @click="goToPage(currentPage + 1)"
    >
      <ChevronRightIcon />
    </Button>

    <Button
      :variant="buttonVariant"
      :size="buttonSize"
      :rounded="buttonRounded"
      aria-label="Go to last page"
      :disabled="currentPage === totalPages"
      @click="goToPage(totalPages)"
    >
      <ChevronsRightIcon />
    </Button>
  </nav>
</template>

// packages/react/src/components/Pagination/Pagination.tsx
import { cn } from "../../utils";

import { DOTS, getPaginationRange } from "./Pagination.utils";

import type { PaginationProps } from "./Pagination.types";
import {
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
} from "../../icons";
import { forwardRef } from "react";
import { Button } from "../Button";

export const Pagination = forwardRef<HTMLElement, PaginationProps>(
  (
    {
      page,
      pageSize,
      total,
      siblingCount = 1,
      className,
      buttonVariant = "primary",
      buttonSize = "md",
      buttonRounded = false,
      onPageChange,
    },
    ref,
  ) => {
    const totalPages = Math.max(1, Math.ceil(total / pageSize));

    const currentPage = Math.min(Math.max(page, 1), totalPages);

    const pages = getPaginationRange({
      total,
      page: currentPage,
      pageSize,
      siblingCount,
    });

    return (
      <nav
        ref={ref}
        className={cn("flex items-center justify-center gap-2", className)}
        aria-label="Pagination"
      >
        <Button
          variant={buttonVariant}
          size={buttonSize}
          rounded={buttonRounded}
          aria-label="Go to first page"
          disabled={currentPage === 1}
          onClick={() => onPageChange(1)}
        >
          <ChevronsLeftIcon />
        </Button>

        <Button
          variant={buttonVariant}
          size={buttonSize}
          rounded={buttonRounded}
          aria-label="Go to previous page"
          disabled={currentPage === 1}
          onClick={() => onPageChange(currentPage - 1)}
        >
          <ChevronLeftIcon />
        </Button>

        {pages.map((item, index) => {
          if (item === DOTS) {
            return (
              <span
                key={`${item}-${index}`}
                aria-hidden="true"
                className="px-2 text-gray-500"
              >
                ...
              </span>
            );
          }

          return (
            <Button
              key={item}
              aria-label={`Page ${item}`}
              aria-current={currentPage === item ? "page" : undefined}
              variant={buttonVariant}
              size={buttonSize}
              rounded={buttonRounded}
              appearance={currentPage === item ? "solid" : "outline"}
              onClick={() => onPageChange(item)}
            >
              {item}
            </Button>
          );
        })}

        <Button
          variant={buttonVariant}
          size={buttonSize}
          rounded={buttonRounded}
          aria-label="Go to next page"
          disabled={currentPage === totalPages}
          onClick={() => onPageChange(currentPage + 1)}
        >
          <ChevronRightIcon />
        </Button>

        <Button
          variant={buttonVariant}
          size={buttonSize}
          rounded={buttonRounded}
          aria-label="Go to last page"
          disabled={currentPage === totalPages}
          onClick={() => onPageChange(totalPages)}
        >
          <ChevronsRightIcon />
        </Button>
      </nav>
    );
  },
);
