// packages/vue/src/components/InputFile/InputFile.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue";

import { CloseIcon, UploadIcon } from "../../icons";
import { cn, normalizeFiles } from "../../utils";
import { inputVariants } from "../../variants/input";

import type { InputFileProps } from "./InputFile.types";
import { useInput } from "../../composables/useInput";

defineOptions({
  name: "InputFile",
  inheritAttrs: false,
});

const props = withDefaults(defineProps<InputFileProps>(), {
  modelValue: null,
  placeholder: "Choose file...",
  preview: false,
  previewShape: "square",
  previewSize: 120,
  rounded: false,
  error: false,
  size: "md",
});

const emit = defineEmits<{
  "update:modelValue": [File | File[] | null];
  "validation-error": [string];
}>();

const { attrs, id, disabled } = useInput();

const inputRef = ref<HTMLInputElement>();

const dragging = ref(false);

const previewUrls = ref<string[]>([]);

const files = computed<File[]>(() => {
  if (!props.modelValue) {
    return [];
  }

  return Array.isArray(props.modelValue)
    ? props.modelValue
    : [props.modelValue];
});

const previewFiles = computed(() =>
  files.value.filter((file) => file.type.startsWith("image/")),
);

const fileName = computed(() => {
  if (files.value.length === 0) {
    return props.placeholder;
  }

  if (files.value.length === 1) {
    return files.value[0].name;
  }

  return `${files.value.length} files selected`;
});

watch(
  previewFiles,
  (value) => {
    previewUrls.value.forEach(URL.revokeObjectURL);

    previewUrls.value = value.map((file) => URL.createObjectURL(file));
  },
  {
    immediate: true,
  },
);

onBeforeUnmount(() => {
  previewUrls.value.forEach(URL.revokeObjectURL);
});

function validate(file: File) {
  if (props.maxSize && file.size > props.maxSize) {
    emit(
      "validation-error",
      `Maximum file size is ${Math.round(props.maxSize / 1024 / 1024)} MB`,
    );

    return false;
  }

  if (props.allowedTypes && !props.allowedTypes.includes(file.type)) {
    emit("validation-error", "Invalid file type");

    return false;
  }

  return true;
}

function handleFiles(fileList: FileList) {
  const validFiles = normalizeFiles(fileList).filter(validate);

  const multiple = attrs.multiple !== undefined;

  emit("update:modelValue", multiple ? validFiles : (validFiles[0] ?? null));
}

function onChange(event: Event) {
  const target = event.target as HTMLInputElement;

  if (!target.files) {
    emit("update:modelValue", null);

    return;
  }

  handleFiles(target.files);
}

function openPicker() {
  if (disabled.value) {
    return;
  }

  inputRef.value?.click();
}

function clear() {
  emit("update:modelValue", null);

  if (inputRef.value) {
    inputRef.value.value = "";
  }
}

function dragOver(event: DragEvent) {
  event.preventDefault();

  if (!disabled.value) {
    dragging.value = true;
  }
}

function dragLeave() {
  dragging.value = false;
}

function drop(event: DragEvent) {
  event.preventDefault();

  dragging.value = false;

  if (disabled.value) {
    return;
  }

  if (!event.dataTransfer?.files.length) {
    return;
  }

  handleFiles(event.dataTransfer.files);
}

const classes = computed(() =>
  cn(
    inputVariants({
      size: props.size,
      rounded: props.rounded,
      error: props.error,
    }),
    "flex w-full items-center justify-between",
    dragging.value && "border-blue-500 bg-blue-50",
    attrs.class,
  ),
);
</script>

<template>
  <div class="w-full">
    <input
      :id="id"
      ref="inputRef"
      v-bind="attrs"
      type="file"
      class="hidden"
      @change="onChange"
    />

    <div class="relative w-full">
      <button
        type="button"
        :disabled="disabled"
        :class="classes"
        @click="openPicker"
        @dragover="dragOver"
        @dragleave="dragLeave"
        @drop="drop"
      >
        <span class="truncate text-left">
          <slot name="filename" :files="files">
            {{ dragging ? "Drop files here..." : fileName }}
          </slot>
        </span>

        <slot name="icon">
          <UploadIcon class="shrink-0 text-gray-500" />
        </slot>
      </button>

      <slot v-if="files.length" name="clear" :clear="clear">
        <button
          type="button"
          class="absolute right-10 top-1/2 -translate-y-1/2 text-gray-400 hover:text-red-500"
          @click.stop="clear"
        >
          <CloseIcon />
        </button>
      </slot>
    </div>

    <slot
      v-if="preview && previewFiles.length"
      name="preview"
      :files="previewFiles"
    >
      <div class="mt-3 flex flex-wrap gap-3">
        <img
          v-for="(url, index) in previewUrls"
          :key="url"
          :src="url"
          :alt="`Preview ${index + 1}`"
          :width="previewSize"
          :height="previewSize"
          :style="{
            width: `${previewSize}px`,
            height: `${previewSize}px`,
          }"
          :class="
            cn(
              'border object-cover',
              previewShape === 'circle' ? 'rounded-full' : 'rounded-md',
            )
          "
        />
      </div>
    </slot>
  </div>
</template>

// packages/react/src/components/InputFile/InputFile.tsx
import { forwardRef, useEffect, useMemo, useRef, useState } from "react";

import { CloseIcon, UploadIcon } from "../../icons";
import { cn, normalizeFiles } from "../../utils";
import { inputVariants } from "../../variants/input";

import type { InputFileProps } from "./InputFile.types";

export const InputFile = forwardRef<HTMLInputElement, InputFileProps>(
  (
    {
      className,
      size,
      rounded,
      error,
      disabled,
      value,
      placeholder = "Choose file...",
      accept,
      multiple,

      preview = false,
      previewShape = "square",
      previewSize = 120,

      maxSize,
      allowedTypes,

      onValidationError,
      onChange,

      renderClearButton,
      renderFileName,
      renderIcon,
      renderPreview,

      ...props
    },
    ref,
  ) => {
    const inputRef = useRef<HTMLInputElement>(null);

    const [previewUrls, setPreviewUrls] = useState<string[]>([]);
    const [dragging, setDragging] = useState(false);

    function validate(file: File): boolean {
      if (maxSize && file.size > maxSize) {
        onValidationError?.(
          `Maximum file size is ${Math.round(maxSize / 1024 / 1024)} MB`,
        );

        return false;
      }

      if (allowedTypes && !allowedTypes.includes(file.type)) {
        onValidationError?.("Invalid file type");

        return false;
      }

      return true;
    }

    function setRefs(node: HTMLInputElement | null) {
      inputRef.current = node;

      if (typeof ref === "function") {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    }

    function openFilePicker() {
      if (disabled) {
        return;
      }

      inputRef.current?.click();
    }

    function handleFiles(files: FileList) {
      const validFiles = normalizeFiles(files).filter(validate);

      if (multiple) {
        onChange?.(validFiles);

        return;
      }

      onChange?.(validFiles[0] ?? null);
    }

    function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
      const files = event.target.files;

      if (!files) {
        onChange?.(null);

        return;
      }

      handleFiles(files);
    }

    function handleClear() {
      onChange?.(null);

      if (inputRef.current) {
        inputRef.current.value = "";
      }

      setPreviewUrls([]);
    }

    function handleDragOver(event: React.DragEvent<HTMLButtonElement>) {
      event.preventDefault();
      event.stopPropagation();

      if (!disabled) {
        setDragging(true);
      }
    }

    function handleDragLeave(_event: React.DragEvent<HTMLButtonElement>) {
      setDragging(false);
    }

    function handleDrop(event: React.DragEvent<HTMLButtonElement>) {
      event.preventDefault();
      event.stopPropagation();

      setDragging(false);

      if (disabled) {
        return;
      }

      const files = event.dataTransfer.files;

      if (!files.length) {
        return;
      }

      handleFiles(files);
    }

    const files = useMemo(() => {
      if (!value) {
        return [];
      }

      return Array.isArray(value) ? value : [value];
    }, [value]);

    const previewFiles = useMemo(() => {
      return files.filter((file) => file.type.startsWith("image/"));
    }, [files]);

    const fileName = useMemo(() => {
      if (files.length === 0) {
        return placeholder;
      }

      if (files.length === 1) {
        return files[0].name;
      }

      return `${files.length} files selected`;
    }, [files, placeholder]);

    useEffect(() => {
      if (previewFiles.length === 0) {
        setPreviewUrls([]);

        return;
      }

      const urls = previewFiles.map((file) => URL.createObjectURL(file));

      setPreviewUrls(urls);

      return () => {
        urls.forEach((url) => URL.revokeObjectURL(url));
      };
    }, [previewFiles]);

    const displayFileName = (() => {
      if (renderFileName) {
        return renderFileName(files);
      }

      if (dragging) {
        return "Drop files here...";
      }

      return fileName;
    })();

    return (
      <div className="w-full">
        <input
          ref={setRefs}
          type="file"
          className="hidden"
          accept={accept}
          multiple={multiple}
          disabled={disabled}
          onChange={handleChange}
          {...props}
        />

        <div className="relative w-full">
          <button
            type="button"
            onClick={openFilePicker}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            disabled={disabled}
            className={cn(
              inputVariants({
                size,
                rounded,
                error,
              }),
              "flex w-full items-center justify-between",
              dragging && "border-blue-500 bg-blue-50",
              className,
            )}
          >
            <span className="truncate text-left">{displayFileName}</span>

            {renderIcon ? (
              renderIcon()
            ) : (
              <UploadIcon className="shrink-0 text-gray-500" />
            )}
          </button>

          {value &&
            (renderClearButton ? (
              renderClearButton(handleClear)
            ) : (
              <button
                type="button"
                onClick={(event) => {
                  event.stopPropagation();
                  handleClear();
                }}
                className="absolute right-10 top-1/2 cursor-pointer -translate-y-1/2 text-gray-400 hover:text-red-500"
                aria-label="Clear file"
              >
                <CloseIcon />
              </button>
            ))}
        </div>

        {preview &&
          previewFiles.length > 0 &&
          (renderPreview ? (
            renderPreview(previewFiles)
          ) : (
            <div className="mt-3 flex flex-wrap gap-3">
              {previewUrls.map((url, index) => (
                <img
                  key={url}
                  src={url}
                  alt={`Preview ${index + 1}`}
                  width={previewSize}
                  height={previewSize}
                  className={cn(
                    "border object-cover",
                    previewShape === "circle" ? "rounded-full" : "rounded-md",
                  )}
                  style={{
                    width: previewSize,
                    height: previewSize,
                  }}
                />
              ))}
            </div>
          ))}
      </div>
    );
  },
);

InputFile.displayName = InputFile.name;
