// packages/vue/src/components/HelperText/HelperText.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";

import { cn } from "../../utils";

import type { HelperTextProps } from "./HelperText.types";

defineOptions({
  name: "HelperText",
  inheritAttrs: false,
});

const props = withDefaults(defineProps<HelperTextProps>(), {
  error: false,
});

const attrs = useAttrs();

const classes = computed(() =>
  cn(
    "text-sm",
    props.error ? "text-red-600" : "text-gray-500 dark:text-gray-400",
    attrs.class,
  ),
);
</script>

<template>
  <p v-bind="attrs" :class="classes">
    <slot />
  </p>
</template>

// packages/react/src/components/HelperText/HelperText.tsx
import { forwardRef } from "react";

import { cn } from "../../utils";

import type { HelperTextProps } from "./HelperText.types";

export const HelperText = forwardRef<HTMLParagraphElement, HelperTextProps>(
  ({ className, error, ...props }, ref) => {
    return (
      <p
        ref={ref}
        className={cn(
          "text-sm",
          error ? "text-red-600" : "text-gray-500 dark:text-gray-400",
          className,
        )}
        {...props}
      />
    );
  },
);

HelperText.displayName = "HelperText";
