// packages/react/src/components/Button/Button.tsx
import { forwardRef } from "react";

import { cn } from "../../utils";
import { buttonVariants } from "../../variants/button";

import type { ButtonProps } from "./Button.types";
import { Spinner } from "../Spinner";

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      className,
      variant,
      appearance,
      size,
      rounded,
      fullWidth,
      loading = false,
      children,
      disabled,
      ...props
    },
    ref,
  ) => {
    return (
      <button
        ref={ref}
        disabled={disabled || loading}
        className={cn(
          buttonVariants({
            variant,
            appearance,
            size,
            rounded,
            fullWidth,
          }),
          className,
        )}
        {...props}
      >
        {loading && <Spinner size={size} />}

        {children}
      </button>
    );
  },
);

Button.displayName = "Button";

// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";

import { cn } from "../../utils";
import { buttonVariants } from "../../variants/button";

import Spinner from "../Spinner/Spinner.vue";

import type { ButtonProps } from "./Button.types";

defineOptions({
  name: "Button",
  inheritAttrs: false,
});

const props = withDefaults(defineProps<ButtonProps>(), {
  appearance: "solid",
  size: "md",
  loading: false,
  disabled: false,
});

const attrs = useAttrs();

const classes = computed(() =>
  cn(
    buttonVariants({
      variant: props.variant,
      appearance: props.appearance,
      size: props.size,
      rounded: props.rounded,
      fullWidth: props.fullWidth,
    }),
    attrs.class,
  ),
);
</script>

<template>
  <button v-bind="attrs" :disabled="disabled || loading" :class="classes">
    <span class="inline-flex items-center gap-2">
      <Spinner v-if="loading" :size="size" />

      <slot />
    </span>
  </button>
</template>
