// packages/react/src/components/Select/Select.tsx
import { createPortal } from "react-dom";
import { forwardRef, useMemo, useRef } from "react";

import { cn } from "../../utils";
import { selectVariants } from "../../variants/select";
import type { SelectOption as Option, SelectProps } from "./Select.types";

import { Spinner } from "../Spinner";
import { SelectOption } from "./SelectOption";
import { ChevronDownIcon, CloseIcon } from "../../icons";

import {
  useDropdown,
  useDropdownPosition,
  useKeyboardNavigation,
  useOutsideClick,
} from "../../hooks";

export const Select = forwardRef<HTMLButtonElement, SelectProps>(
  (
    {
      className,
      size,
      rounded,
      error,
      value,
      options,
      labelKey,
      valueKey,
      placeholder = "Select...",
      loading,
      loadingText = "Loading...",
      emptyText = "No data",
      disabled,
      clearable,
      clearIcon,
      clearIconClassName,
      renderValue,
      renderOption,
      onChange,
      ...props
    },
    ref,
  ) => {
    const rootRef = useRef<HTMLDivElement>(null);
    const triggerRef = useRef<HTMLButtonElement>(null);
    const dropdownRef = useRef<HTMLDivElement>(null);

    const { open, closeDropdown, toggleDropdown } = useDropdown({
      disabled,
    });

    const selectedOption = useMemo(() => {
      return options.find((item) => String(item[valueKey]) === String(value));
    }, [options, value, valueKey]);

    const selectedIndex = useMemo(() => {
      return options.findIndex(
        (option) => String(option[valueKey]) === String(value),
      );
    }, [options, value, valueKey]);

    const selectedText = (() => {
      if (!selectedOption) {
        return placeholder;
      }

      if (renderValue) {
        return renderValue(selectedOption);
      }

      return String(selectedOption[labelKey]);
    })();

    function handleSelect(option: Option) {
      onChange?.(option[valueKey] as string | number, option);

      closeDropdown();
    }

    useOutsideClick({
      refs: [rootRef, dropdownRef],
      onOutsideClick: closeDropdown,
    });

    const { dropdownStyle } = useDropdownPosition({
      open,
      triggerRef,
    });

    const { activeIndex, optionRefs, handleKeyDown } = useKeyboardNavigation({
      open,
      options,
      selectedIndex,
      onSelect: handleSelect,
      onClose: closeDropdown,
    });

    function setRefs(node: HTMLButtonElement | null) {
      triggerRef.current = node;

      if (typeof ref === "function") {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    }

    const showClear =
      clearable &&
      !disabled &&
      !loading &&
      value !== undefined &&
      value !== null &&
      value !== "";

    function handleClear(e: React.MouseEvent) {
      e.preventDefault();
      e.stopPropagation();

      onChange?.(undefined);

      closeDropdown();
    }

    const dropdownContent = (() => {
      if (loading) {
        return (
          <div className="flex items-center justify-center gap-2 p-3 text-sm">
            <Spinner size="sm" />
            {loadingText}
          </div>
        );
      }

      if (options.length === 0) {
        return (
          <div className="p-3 text-center text-sm text-muted-foreground">
            {emptyText}
          </div>
        );
      }

      return options.map((option, index) => (
        <SelectOption
          key={String(option[valueKey])}
          option={option}
          labelKey={labelKey}
          selected={String(option[valueKey]) === String(value)}
          onSelect={handleSelect}
          active={index === activeIndex}
          renderOption={renderOption}
          optionRef={(node) => {
            optionRefs.current[index] = node;
          }}
        />
      ));
    })();

    return (
      <div ref={rootRef} className="relative w-full">
        <button
          ref={setRefs}
          type="button"
          disabled={disabled}
          onClick={toggleDropdown}
          onKeyDown={handleKeyDown}
          className={cn(
            selectVariants({
              size,
              rounded,
              error,
            }),
            className,
          )}
          {...props}
        >
          <span className="truncate flex-1 text-left">{selectedText}</span>

          <div className="flex items-center gap-2">
            {showClear && (
              <button
                type="button"
                tabIndex={-1}
                onClick={handleClear}
                aria-label="Clear selection"
                className="flex items-center justify-center"
              >
                {clearIcon ?? (
                  <CloseIcon
                    className={cn(
                      "h-4 w-4 text-gray-400 hover:text-gray-600",
                      clearIconClassName,
                    )}
                  />
                )}
              </button>
            )}

            <ChevronDownIcon
              className={cn("transition-transform", open && "rotate-180")}
            />
          </div>
        </button>

        {open &&
          createPortal(
            <div
              ref={dropdownRef}
              style={dropdownStyle}
              className={cn(
                "max-h-64 overflow-auto border bg-white shadow-md",
                "dark:border-gray-700",
                "dark:bg-gray-900",
                "text-gray-900",
                "dark:text-gray-100",
                rounded ? "rounded-2xl" : "rounded-md",
              )}
            >
              {dropdownContent}
            </div>,
            document.body,
          )}
      </div>
    );
  },
);

Select.displayName = "Select";

// packages/vue/src/components/Select/Select.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import { cn } from "../../utils";
import { selectVariants } from "../../variants/select";

import { useInput } from "../../composables/useInput";
import { useDropdown } from "../../composables/useDropdown";
import { useDropdownPosition } from "../../composables/useDropdownPosition";
import { useKeyboardNavigation } from "../../composables/useKeyboardNavigation";
import { useOutsideClick } from "../../composables/useOutsideClick";

import Spinner from "../Spinner/Spinner.vue";

import { ChevronDownIcon, CloseIcon } from "../../icons";

import type { Option, SelectProps } from "./Select.types";

defineOptions({
  name: "Select",
  inheritAttrs: false,
});

const props = withDefaults(defineProps<SelectProps>(), {
  placeholder: "Select...",
  loading: false,
  loadingText: "Loading...",
  emptyText: "No data",
  clearable: false,
  size: "md",
  error: false,
  rounded: false,
});

const emit = defineEmits<{
  "update:modelValue": [string | number | undefined];
  change: [string | number | undefined, Option | undefined];
}>();

const { attrs, disabled } = useInput();

const rootRef = ref<HTMLElement>();
const triggerRef = ref<HTMLElement>();
const dropdownRef = ref<HTMLElement>();

const { open, closeDropdown, toggleDropdown } = useDropdown(
  () => !!disabled.value,
);

const selectedOption = computed(() =>
  props.options.find(
    (item) => String(item[props.valueKey]) === String(props.modelValue),
  ),
);

const selectedIndex = computed(() =>
  props.options.findIndex(
    (item) => String(item[props.valueKey]) === String(props.modelValue),
  ),
);

function handleSelect(option: Option) {
  const value = option[props.valueKey] as string | number;

  emit("update:modelValue", value);
  emit("change", value, option);

  closeDropdown();
}

const { activeIndex, optionRefs, handleKeyDown } = useKeyboardNavigation({
  open,
  options: computed(() => props.options),
  selectedIndex,
  onSelect: handleSelect,
  onClose: closeDropdown,
});

useOutsideClick([rootRef, dropdownRef], closeDropdown);

const { dropdownStyle } = useDropdownPosition(open, triggerRef);

const showClear = computed(
  () =>
    props.clearable &&
    !disabled.value &&
    !props.loading &&
    props.modelValue !== undefined &&
    props.modelValue !== null &&
    props.modelValue !== "",
);

function clear() {
  emit("update:modelValue", undefined);
  emit("change", undefined, undefined);

  closeDropdown();
}

const classes = computed(() =>
  cn(
    selectVariants({
      size: props.size,
      rounded: props.rounded,
      error: props.error,
    }),
    attrs.class,
  ),
);
</script>

<template>
  <div ref="rootRef" class="relative w-full">
    <button
      ref="triggerRef"
      v-bind="attrs"
      type="button"
      :disabled="disabled"
      :class="classes"
      @click="toggleDropdown"
      @keydown="handleKeyDown"
    >
      <span class="flex-1 truncate text-left">
        <slot name="value" :option="selectedOption">
          {{ selectedOption ? selectedOption[labelKey] : placeholder }}
        </slot>
      </span>

      <div class="flex items-center gap-2">
        <button
          v-if="showClear"
          type="button"
          tabindex="-1"
          class="flex items-center justify-center"
          @click.stop="clear"
        >
          <slot name="clear">
            <CloseIcon class="h-4 w-4 text-gray-400 hover:text-gray-600" />
          </slot>
        </button>

        <ChevronDownIcon
          :class="cn('transition-transform', open && 'rotate-180')"
        />
      </div>
    </button>

    <Teleport to="body">
      <div
        v-if="open"
        ref="dropdownRef"
        :style="dropdownStyle"
        :class="
          cn(
            'max-h-64 overflow-auto border bg-white shadow-md',
            'dark:border-gray-700 dark:bg-gray-900',
            'text-gray-900 dark:text-gray-100',
            rounded ? 'rounded-2xl' : 'rounded-md',
          )
        "
      >
        <template v-if="loading">
          <div class="flex items-center justify-center gap-2 p-3 text-sm">
            <Spinner size="sm" />
            {{ loadingText }}
          </div>
        </template>

        <template v-else-if="options.length === 0">
          <div class="p-3 text-center text-sm text-gray-500">
            {{ emptyText }}
          </div>
        </template>

        <template v-else>
          <button
            v-for="(option, index) in options"
            :key="String(option[valueKey])"
            :ref="
              (el) => {
                optionRefs[index] = el as HTMLButtonElement | null;
              }
            "
            type="button"
            :class="
              cn(
                'flex w-full items-center px-3 py-2 text-left text-sm transition-colors',
                'hover:bg-gray-100 dark:hover:bg-gray-800',
                String(option[valueKey]) === String(modelValue) &&
                  'bg-gray-100 font-medium dark:bg-gray-800',
                activeIndex === index && 'bg-blue-100 dark:bg-blue-900',
              )
            "
            @click="handleSelect(option)"
          >
            <slot
              name="option"
              :option="option"
              :selected="String(option[valueKey]) === String(modelValue)"
              :active="activeIndex === index"
            >
              {{ option[labelKey] }}
            </slot>
          </button>
        </template>
      </div>
    </Teleport>
  </div>
</template>
