// packages/react/src/components/Spinner/Spinner.tsx
import { forwardRef } from "react";

import { cn } from "../../utils";
import { spinnerVariants } from "../../variants/spinner";

import type { SpinnerProps } from "./Spinner.types";

export const Spinner = forwardRef<HTMLSpanElement, SpinnerProps>(
  ({ className, size, ...props }, ref) => {
    return (
      <span
        ref={ref}
        className={cn(
          spinnerVariants({
            size,
          }),
          className,
        )}
        {...props}
      />
    );
  },
);

Spinner.displayName = "Spinner";

// packages/vue/src/components/Spinner/Spinner.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";

import { spinnerVariants } from "../../variants/spinner";
import { cn } from "../../utils";

import type { SpinnerProps } from "./Spinner.types";

defineOptions({
  name: "Spinner",
  inheritAttrs: false,
});

const props = withDefaults(defineProps<SpinnerProps>(), {
  size: "md",
});

const attrs = useAttrs();

const classes = computed(() =>
  cn(
    spinnerVariants({
      size: props.size,
    }),
    attrs.class,
  ),
);
</script>

<template>
  <span v-bind="attrs" :class="classes" />
</template>
