// packages/react/src/components/Table/Table.tsx
import { forwardRef } from "react";

import { Checkbox } from "../Checkbox";

import { cn } from "../../utils";

import {
  tableCellVariants,
  tableHeadVariants,
  tableHeaderVariants,
  tableRowVariants,
  tableVariants,
} from "../../variants/table";

import { TableSortButton } from "./TableSortButton";
import {
  getNextSortDirection,
  getRowKeys,
  getSelectionState,
  isRowSelected,
  renderCellValue,
  toggleAllRows,
  toggleRowSelection,
} from "./Table.utils";

import type { TableProps } from "./Table.types";
import type { ForwardedRef, ReactElement } from "react";

function TableComponent<T extends object, K extends keyof T>(
  {
    columns,
    data,
    rowKey,
    striped = true,
    className,
    sorting,
    selection,
    emptyText,
    ...props
  }: Readonly<TableProps<T, K>>,
  ref: ForwardedRef<HTMLDivElement>,
) {
  const rowKeys = getRowKeys(data, rowKey);

  const selectionState = selection
    ? getSelectionState(selection.selectedRowKeys, rowKeys)
    : null;

  const columnCount = columns.length + (selection ? 1 : 0);

  function handleSort(field: keyof T) {
    if (!sorting?.onSort) {
      return;
    }

    const direction = getNextSortDirection(
      sorting.field === field ? sorting.direction : null,
    );

    sorting.onSort(direction ? field : undefined, direction);
  }

  return (
    <div
      ref={ref}
      className={cn("w-full overflow-x-auto", className)}
      {...props}
    >
      <table className={tableVariants()}>
        <thead className={tableHeaderVariants()}>
          <tr>
            {selection && selectionState && (
              <th className={tableHeadVariants()}>
                <Checkbox
                  checked={selectionState.checked}
                  indeterminate={selectionState.indeterminate}
                  onCheckedChange={() =>
                    selection.onChange?.(
                      toggleAllRows(selection.selectedRowKeys, rowKeys),
                    )
                  }
                />
              </th>
            )}

            {columns.map((column) => (
              <th
                key={String(column.key)}
                style={{
                  width: column.width,
                }}
                className={cn(
                  tableHeadVariants(),
                  column.align === "center" && "text-center",
                  column.align === "right" && "text-right",
                )}
              >
                {column.sortable ? (
                  <TableSortButton
                    active={sorting?.field === column.key}
                    direction={sorting?.direction}
                    onClick={() => handleSort(column.key)}
                  >
                    {column.title}
                  </TableSortButton>
                ) : (
                  column.title
                )}
              </th>
            ))}
          </tr>
        </thead>

        <tbody>
          {data.length === 0 ? (
            <tr>
              <td
                colSpan={columnCount}
                className={cn(
                  tableCellVariants(),
                  "py-10 text-center text-gray-600 dark:text-gray-200",
                )}
              >
                {emptyText ?? "No data"}
              </td>
            </tr>
          ) : (
            data.map((row, rowIndex) => {
              const rowValue = row[rowKey];

              const key =
                typeof rowValue === "string" || typeof rowValue === "number"
                  ? rowValue
                  : rowIndex;

              return (
                <tr
                  key={key}
                  className={tableRowVariants({
                    striped,
                  })}
                >
                  {selection && (
                    <td className={tableCellVariants()}>
                      <Checkbox
                        checked={isRowSelected(
                          selection.selectedRowKeys,
                          rowValue,
                        )}
                        onCheckedChange={() =>
                          selection.onChange?.(
                            toggleRowSelection(
                              selection.selectedRowKeys,
                              rowValue,
                            ),
                          )
                        }
                      />
                    </td>
                  )}

                  {columns.map((column) => {
                    const value = row[column.key];

                    return (
                      <td
                        key={String(column.key)}
                        className={cn(
                          tableCellVariants(),
                          column.align === "center" && "text-center",
                          column.align === "right" && "text-right",
                        )}
                      >
                        {column.render
                          ? column.render(value, row, rowIndex)
                          : renderCellValue(value)}
                      </td>
                    );
                  })}
                </tr>
              );
            })
          )}
        </tbody>
      </table>
    </div>
  );
}

TableComponent.displayName = "Table";

type TableComponentType = <T extends object, K extends keyof T = keyof T>(
  props: TableProps<T, K> & {
    ref?: React.Ref<HTMLDivElement>;
  },
) => ReactElement | null;

export const Table = forwardRef(
  TableComponent,
) as unknown as TableComponentType;

// packages/vue/src/components/Table/Table.vue
<script setup lang="ts">
import { computed } from "vue";

import { cn } from "../../utils";

import {
  tableCellVariants,
  tableHeadVariants,
  tableHeaderVariants,
  tableRowVariants,
  tableVariants,
} from "../../variants/table";

import Checkbox from "../Checkbox/Checkbox.vue";
import TableSortButton from "./TableSortButton.vue";

import {
  getNextSortDirection,
  getRowKey,
  getRowKeys,
  getSelectionState,
  isRowSelected,
  renderCellValue,
  toggleAllRows,
  toggleRowSelection,
} from "./Table.utils";

import type { TableProps } from "./Table.types";

defineOptions({
  name: "Table",
});

const props = withDefaults(defineProps<TableProps>(), {
  striped: true,
  emptyText: "No data",
});

const emit = defineEmits<{
  sort: [field: string | undefined, direction: "asc" | "desc" | null];

  selectionChange: [keys: Array<string | number>];
}>();

const rowKeys = computed(() => getRowKeys(props.data, props.rowKey));

const selectionState = computed(() => {
  if (!props.selection) {
    return null;
  }

  return getSelectionState(props.selection.selectedRowKeys, rowKeys.value);
});

const columnCount = computed(
  () => props.columns.length + (props.selection ? 1 : 0),
);

function handleSort(field: string) {
  if (!props.sorting) {
    return;
  }

  const direction = getNextSortDirection(
    props.sorting.field === field ? props.sorting.direction : null,
  );

  emit("sort", direction ? field : undefined, direction);
}

function toggleAllSelection() {
  if (!props.selection) {
    return;
  }

  emit(
    "selectionChange",
    toggleAllRows(props.selection.selectedRowKeys, rowKeys.value),
  );
}

function toggleSelection(key: string | number) {
  if (!props.selection) {
    return;
  }

  emit(
    "selectionChange",
    toggleRowSelection(props.selection.selectedRowKeys, key),
  );
}
</script>

<template>
  <div class="w-full overflow-x-auto">
    <table :class="tableVariants()">
      <thead :class="tableHeaderVariants()">
        <tr>
          <th v-if="selection && selectionState" :class="tableHeadVariants()">
            <Checkbox
              :checked="selectionState.checked"
              :indeterminate="selectionState.indeterminate"
              @update:model-value="toggleAllSelection"
            />
          </th>

          <th
            v-for="column in columns"
            :key="column.key"
            :style="{
              width: column.width,
            }"
            :class="
              cn(
                tableHeadVariants(),
                column.align === 'center' && 'text-center',
                column.align === 'right' && 'text-right',
              )
            "
          >
            <TableSortButton
              v-if="column.sortable"
              :active="sorting?.field === column.key"
              :direction="sorting?.direction"
              @click="handleSort(column.key)"
            >
              <slot :name="`header-${column.key}`" :column="column">
                {{ column.title }}
              </slot>
            </TableSortButton>

            <template v-else>
              <slot :name="`header-${column.key}`" :column="column">
                {{ column.title }}
              </slot>
            </template>
          </th>
        </tr>
      </thead>

      <tbody>
        <tr v-if="data.length === 0">
          <td
            :colspan="columnCount"
            :class="
              cn(
                tableCellVariants(),
                'py-10 text-center text-gray-600 dark:text-gray-200',
              )
            "
          >
            <slot name="empty">
              {{ emptyText }}
            </slot>
          </td>
        </tr>

        <tr
          v-for="(row, rowIndex) in data"
          v-else
          :key="getRowKey(row, rowKey, rowIndex)"
          :class="
            tableRowVariants({
              striped,
            })
          "
        >
          <td v-if="selection" :class="tableCellVariants()">
            <Checkbox
              :model-value="
                isRowSelected(
                  selection.selectedRowKeys,
                  row[rowKey] as string | number,
                )
              "
              @update:model-value="
                toggleSelection(row[rowKey] as string | number)
              "
            />
          </td>

          <td
            v-for="column in columns"
            :key="column.key"
            :class="
              cn(
                tableCellVariants(),
                column.align === 'center' && 'text-center',
                column.align === 'right' && 'text-right',
              )
            "
          >
            <slot
              :name="column.key"
              :value="row[column.key]"
              :record="row"
              :index="rowIndex"
            >
              {{ renderCellValue(row[column.key]) }}
            </slot>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
