// packages/vue/src/components/Label/Label.vue
<script setup lang="ts">
import { computed, inject, useAttrs } from "vue";

import { cn } from "../../utils";

import type { LabelProps } from "./Label.types";
import { formControlKey } from "../../composables/form-control";

defineOptions({
  name: "Label",
  inheritAttrs: false,
});

const props = defineProps<LabelProps>();

const attrs = useAttrs();

const formControl = inject(formControlKey, null);

const htmlFor = computed(() => props.htmlFor ?? formControl?.id.value);
</script>

<template>
  <label
    v-bind="attrs"
    :for="htmlFor"
    :class="
      cn('text-sm font-medium text-gray-900 dark:text-gray-100', attrs.class)
    "
  >
    <slot />
  </label>
</template>

// packages/react/src/components/Label/Label.tsx
import { forwardRef } from "react";

import { cn } from "../../utils";

import { useFormControl } from "../FormControl/FormControl.context";

import type { LabelProps } from "./Label.types";

export const Label = forwardRef<HTMLLabelElement, LabelProps>(
  ({ className, htmlFor, ...props }, ref) => {
    const formControl = useFormControl();

    return (
      <label
        ref={ref}
        htmlFor={htmlFor ?? formControl?.id}
        className={cn(
          "text-sm font-medium text-gray-900 dark:text-gray-100",
          className,
        )}
        {...props}
      />
    );
  },
);

Label.displayName = "Label";
